name: Issue Response
on:
  issues:
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/respost@v0.1.0
        with:
          title: Your issue has been closed!
          body: |-
            If your issue was closed **and not resolved** by one of our developers it may fall under one or more of these categories:

            * Your issue was already reported, it is a duplicate. Check the other open issues first before posting!
            * You posted an error without using pastebin. Please always post errors via pastebin.

            Otherwise, thank you for reporting this problem.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_ME }}